config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :subjects 
  resources :books
  get 'users/show'
  get '/pages/texte'
  get '/pages/bilder'
  get '/pages/formulare'
  get 'helloworld', to: 'helloworld#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :subject
    validates_presence_of :title
    validates_numericality_of :price, :message => "Error Message"
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :books, dependent: :restrict_with_error
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
    end

    def show
        @book = Book.find(params[:id])
    end 

    def new 
        @book = Book.new
        @subjects = Subject.all
    end 

    def create 
        @book = Book.new(book_params) 
        if @book.save 
            redirect_to action: "index" 
        else 
            @subjects = Subject.all 
            render action: "new" 
        end 
    end 

    def book_params 
        params.require(:book).permit(:title, :price, :subject_id, :description) 
    end

    def edit 
        @book = Book.find(params[:id]) 
        @subjects = Subject.all
    end 

    def update 
        @book = Book.find(params[:id]) 
        if @book.update(book_params) 
            redirect_to action: "index" 
        else 
            @subjects = Subject.all 
            render action: "edit"
        end
    end 

    def destroy 
        Book.find(params[:id]).destroy 
        redirect_to action: "index"
    end
end

app/controllers/helloworld_controller.rb
class HelloworldController < ApplicationController
  def index
    i = 1
    @output = ""
    while i < 100 do
      @output += i.to_s + "<br>"
      i += 1
    end
    @output += "Ich komme..."
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def bilder
  end
  def texte
  end
  def formulare
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
    def index
        @subjects = Subject.all
    end

    def show
        @subject = Subject.find(params[:id])
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/helloworld_helper.rb
module HelloworldHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class= "marginform">
  <%= form_for :book, url: {action: "update"} do |f| %>
    <div class="form-row">
      <div class="form-group col-md-4">
        <label>Titel</label> <br/>
        <%= f.text_field :title, class: "form-control", placeholder: "Titel" %>
      </div>
      <div class="form-group col-md-4">
        <label>Preis</label> <br/>
        <%= f.text_field :price, class: "form-control", placeholder: "Preis"  %>
      </div>
      <div class="form-group col-md-4">
        <label>Thema</label> <br/>
        <%= f.collection_select :subject_id, @subjects, :id, :name, class: "form-control", placeholder: "Preis"  %>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-11">
        <label>Beschreibung</label>
        <%= f.text_area :description, class: "form-control", placeholder: "Beschreibung"  %>
      </div>
    </div>
    <%= submit_tag "Buch speichern", class:"btn btn-primary" %>
    <%= link_to "Abbrechen", books_path , class: "btn btn-primary"%>
  <% end %>
</div>

app/views/books/index.html.erb
<div class = "container">
  <table class = "table table-hover">
    <thead class = "threa-light">
      <tr>
        <th>
          Titel
        </th>
        <th colspan="2">Aktion</th>
      </tr>
    </thead>
    <tbody> <% @books.each do |b| %>
        <tr>
          <td><%= link_to b.title, book_path(b.id) %></td>
          <td><%= link_to "Ändern", edit_book_path(b.id) %></td>
          <td><%= link_to "Löschen", book_path(b.id), method: :delete, data: { confirm: "Sind Sie sicher?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Neues Buch erfassen", new_book_path %><br/>
  <%= link_to "Fachgebiete", subjects_path %><br/>
</div>

app/views/books/new.html.erb
<div class= "marginform">
  <%= form_for :book, url: {action: "create"} do |f| %>
    <div class="form-row">
      <div class="form-group col-md-4">
        <label>Titel</label> <br/>
        <%= f.text_field :title, class: "form-control", placeholder: "Titel" %>
      </div>
      <div class="form-group col-md-4">
        <label>Preis</label> <br/>
        <%= f.text_field :price, class: "form-control", placeholder: "Preis"  %>
      </div>
      <div class="form-group col-md-4">
        <label>Thema</label> <br/>
        <%= f.collection_select :subject_id, @subjects, :id, :name, class: "form-control", placeholder: "Preis"  %>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-11">
        <label>Beschreibung</label>
        <%= f.text_area :description, class: "form-control", placeholder: "Beschreibung"  %>
      </div>
    </div>
    <%= submit_tag "Buch speichern", class:"btn btn-primary" %>
    <%= link_to "Abbrechen", books_path , class: "btn btn-primary"%>
  <% end %>
</div>

app/views/books/show.html.erb
    <body>
  <div class="center">
    <div class="page">
      <h1><%=@book.title%></h1>
      <p>
        Preis: <%=@book.price%><br>
        Thema: <%= link_to @book.subject.name, subject_path(@book.subject_id) %><br>
        Beschreibung: <%=@book.description%><br>
        Erstelldatum: <%=@book.created_at%><br>
      </p>
    </div>
    <%= link_to 'Bücherliste', books_path%>
  </div>
</body>

app/views/helloworld/index.html.erb
<h1>Hello World</h1>
<p>Ergebnis vom Versteckspiel:</p>
<p>
<%== @output %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Carousel Template for Bootstrap</title>
      </head>
      <body>
        <header>
          <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="/">Carousel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/pages/texte">Texte & Tabellen</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/pages/formulare">Formulare</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="/pages/bilder">Bilder<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="/users/show">Show Users<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" href="#">Disabled</a>
                </li>
                <li class="nav-item">
                  <%= link_to 'Bücherliste', books_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Fachegebiete', subjects_path, class: 'nav-link' %>
                </li>
              </ul>
              <form class="form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
          </nav>
        </header>
        <%= yield %>
      </body>
    </html>

app/views/pages/bilder.html.erb
<main>
  <div class="p-2 mb-2 bg-warning opacity-25 text-dark">
    <h1 class="mt-4 text-center">
      Bootstrap Demo Bilder
    </h1>
  </div>
  <h2> Bilder quer, max 4 pro Zeile </h2>
  <div class="row row-cols-md-4">
    <%= image_tag("pexels-photo-6677734.png", class: 'img-thumbnail' )%>
    <%= image_tag("pexels-photo-7210061.jpeg", class: 'img-thumbnail' )%>
    <%= image_tag("pexels-photo-7210062.jpeg", class: 'img-thumbnail' )%>
    <%= image_tag("pexels-photo-7296711.jpeg", class: 'img-thumbnail' )%>
    <%= image_tag("pexels-photo-7565956.webp", class: 'img-thumbnail' )%>
  </div>
  <h2> Bilder hoch, max 6 pro Zeile </h2>
  <div class="row row-cols-md-6">
    <%= image_tag("pexels-photo-10912815.jpeg", class: 'img-thumbnail' )%>
    <%= image_tag("pexels-photo-10925348.webp", class: 'img-thumbnail' )%>
    <%= image_tag("pexels-photo-10955577.jpeg", class: 'img-thumbnail' )%>
    <%= image_tag("pexels-photo-10980701.webp", class: 'img-thumbnail' )%>
    <%= image_tag("pexels-photo-11059192.jpeg", class: 'img-thumbnail' )%>
  </div>
</main>

app/views/pages/formulare.html.erb
<main>
  <div class="p-2 mb-2 bg-success opacity-25 text-dark">
    <h1 class="mt-4 text-center">
      Bootstrap Demo Formulare & Buttons
    </h1>
  </div>
  <div class="text-center">
    <h3 class="mt-4">Formular mit Inputfeldern und Buttons</h3>
    <div class="input-group">
      <div class="input-group-prepend">
        <div class="input-group-text">@</div>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email angeben">
      </div>
    </div>
    <br/>
    <label for="exampleFormControlTextarea1">Example textarea</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
</main>

app/views/pages/home.html.erb
<main role="main">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="first-slide" src="/assets/placeholder.png" alt="First slide">
        <div class="container">
          <div class="carousel-caption text-left">
            <h1>Wilkommen auf meiner Homepage.</h1>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="second-slide" src="/assets/placeholder.png" alt="Second slide">
        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="third-slide" src="/assets/placeholder.png" alt="Third slide">
        <div class="container">
          <div class="carousel-caption text-right">
            <h1>One more for good measure.</h1>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <!-- Marketing messaging and featurettes
      ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->
  <div class="container marketing">
    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
        <img class="rounded-circle" src="/assets/placeholder.png" alt="Generic placeholder image" width="140" height="140">
        <h2>Texte & Tabellen</h2>
        <p>Auf dieser Seite werden Texte, Spaltenlayout und Tabellen verwendet</p>
        <p><a class="btn btn-secondary" href="pages/texte" role="button">Seite anzeigen &raquo;</a></p>
      </div>
      <!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <img class="rounded-circle" src="/assets/placeholder.png" alt="Generic placeholder image" width="140" height="140">
        <h2>Bilder</h2>
        <p>Seite um einen Bilderindex (Thumbnails) und die Anzeige von Bildern zu zeigen.</p>
        <p><a class="btn btn-secondary" href="pages/bilder" role="button">Seite anzeigen &raquo;</a></p>
      </div>
      <!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <img class="rounded-circle" src="/assets/placeholder.png" alt="Generic placeholder image" width="140" height="140">
        <h2>Formulare & Buttons</h2>
        <p>Auf dieser Seite werden verschiedene Formularelemente und Buttons verwendet.</p>
        <p><a class="btn btn-secondary" href="pages/formulare" role="button">Seite anzeigen &raquo;</a></p>
      </div>
      <!-- /.col-lg-4 -->
    </div>
    <!-- /.row -->
    <!-- START THE FEATURETTES -->
    <hr class="featurette-divider">
    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5">
        <img class="rounded-circle" src="/assets/400X400.png" alt="Generic placeholder image">
      </div>
    </div>
    <hr class="featurette-divider">
    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <img class="rounded-circle" src="/assets/400X400.png" alt="Generic placeholder image">
      </div>
    </div>
    <hr class="featurette-divider">
    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5">
        <img class="rounded-circle" src="/assets/400X400.png" alt="Generic placeholder image">
      </div>
    </div>
    <hr class="featurette-divider">
    <!-- /END THE FEATURETTES -->
  </div>
  <!-- /.container -->
  <!-- FOOTER -->
  <footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; 2017-2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main>

app/views/pages/texte.html.erb
<main>
  <div class="p-2 mb-2 bg-success opacity-25 text-dark">
    <h1 class="mt-4 text-center">
      Bootstrap Demo Texte & Tabellen
    </h1>
  </div>
  <div class="container">
    <div class="row">
      <div class="col" >
        <h3>One of 2 columns</h3>
        <h4>Hiiiiii</h4>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci ipsum, tincidunt in tempus ac, molestie vel arcu. Proin quis fermentum orci, id convallis felis. Etiam dignissim ligula porta, mattis augue pulvinar, laoreet sapien. Donec feugiat felis nec mauris lobortis, vitae varius magna viverra. Aliquam in nisl lectus.</p>
        <h4>Welcome</h4>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci ipsum, tincidunt in tempus ac, molestie vel arcu. Proin quis fermentum orci, id convallis felis. Etiam dignissim ligula porta, mattis augue pulvinar, laoreet sapien. Donec feugiat felis nec mauris lobortis, vitae varius magna viverra. Aliquam in nisl lectus.</p>
      </div>
      <div class="col">
        <h3>One of 2 columns</h3>
        <h4>Hiiiiii</h4>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci ipsum, tincidunt in tempus ac, molestie vel arcu. Proin quis fermentum orci, id convallis felis. Etiam dignissim ligula porta, mattis augue pulvinar, laoreet sapien. Donec feugiat felis nec mauris lobortis, vitae varius magna viverra. Aliquam in nisl lectus.</p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci ipsum, tincidunt in tempus ac, molestie vel arcu. Proin quis fermentum orci, id convallis felis. Etiam dignissim ligula porta, mattis augue pulvinar, laoreet sapien. Donec feugiat felis nec mauris lobortis, vitae varius magna viverra. Aliquam in nisl lectus.</p>
    </div>
  </div>
</div>
<h3>Tabelle</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@lol</td>
      <td>mark.otto@lol.com</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
      <td>jacob.thornton@fat.com</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
      <td>larry.thebird@twitter.com</td>
    </tr>
  </tbody>
</table>
</main>

app/views/subjects/index.html.erb
<div class = "container">
  <h1> Fachgebiete </h1>
  <table class = "table table-hover">
    <thead class = "threa-light">
      <tr>
        <th>
          Name
        </th>
      </tr>
    </thead>
    <tbody> <% @subjects.each do |s| %>
        <tr>
          <td><%= link_to s.name, show_subject_path(s.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/subjects/show.html.erb
<div class = "container">
  <h1> Bücher im Fachgebiet <%= @subject.name %> </h1>
  <table class = "table table-hover">
    <thead class = "threa-light">
      <tr>
        <th>
          Name
        </th>
      </tr>
    </thead>
    <tbody> <% @subject.books.each do |b| %>
        <tr>
          <td><%= link_to b.title, show_book_path(b.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Fachegebiete', subjects_path%>
</div>

app/views/users/show.html.erb
<h1>Userlist</h1>
<p> Hier sind die User aufgelistet </p>
<p>Anzahl Datensätze: <%= User.count %></p>
<ol>
  <% User.all.each do |u| %>
    <li>
      <p class="m-0"><%=u.name%></p>
      <p class="m-0">Email: <a href="mailto:<%=u.email%>"><%=u.email%></a></p>
      <p>Alter: <%=u.age%></p>
    </li>
  <%end%>
</ol>